name: CI
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: ["3.10", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.py }} }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Lint & Type
        run: |
          python -m ruff check .
          python -m ruff format --check .
          python -m mypy fedenet
      - name: Tests
        run: pytest -q
