# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: ["3.10", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: pip

      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"

      - name: Ruff (lint)
        run: python -m ruff check .

      - name: Ruff (format check)
        run: python -m ruff format --check .

      - name: MyPy (types)
        run: python -m mypy fedenet

      - name: Pytest (with coverage)
        run: |
          pytest -q \
            --cov=fedenet \
            --cov-report=xml \
            --cov-report=term-missing \
            --junitxml=pytest.xml \
            --cov-fail-under=85

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: os-${{ matrix.os }},py-${{ matrix.py }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload test & coverage artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.os }}-py${{ matrix.py }}
          path: |
            coverage.xml
            pytest.xml



